{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 15,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Dependencies\n",
    "import tweepy\n",
    "import numpy as np\n",
    "import pandas as pd\n",
    "\n",
    "# Import and Initialize Sentiment Analyzer\n",
    "from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer\n",
    "analyzer = SentimentIntensityAnalyzer()\n",
    "\n",
    "# Twitter API Keys\n",
    "try:\n",
    "    from config import (consumer_key, \n",
    "                        consumer_secret, \n",
    "                        access_token, \n",
    "                        access_token_secret)\n",
    "except:\n",
    "    consumer_key = os.environ[\"CONSUMER_KEY\"]\n",
    "    consumer_secret = os.environ[\"CONSUMER_SECRET\"]\n",
    "    access_token = os.environ[\"ACCESS_TOKEN\"]\n",
    "    access_token_secret = os.environ[\"ACCESS_TOKEN_SECRET\"]\n",
    "    \n",
    "# Setup Tweepy API Authentication\n",
    "auth = tweepy.OAuthHandler(consumer_key, consumer_secret)\n",
    "auth.set_access_token(access_token, access_token_secret)\n",
    "api = tweepy.API(auth, parser=tweepy.parsers.JSONParser())"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 16,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "{'Airline': '@SouthwestAir', 'Compound Score': 0.1622003076923077, 'Pos Score': 0.13137076923076924, 'Neg Score': 0.05215538461538461, 'Neut Score': 0.8164676923076922, 'Oldest Tweet': 'Fri Jul 06 17:00:39 +0000 2018'}\n",
      "-----\n",
      "{'Airline': '@AmericanAir', 'Compound Score': 0.015757937806873977, 'Pos Score': 0.08579214402618657, 'Neg Score': 0.07985924713584287, 'Neut Score': 0.8343502454991817, 'Oldest Tweet': 'Sat Jul 07 02:51:54 +0000 2018'}\n",
      "-----\n",
      "{'Airline': '@SpiritAirlines', 'Compound Score': -0.01317603174603175, 'Pos Score': 0.09164761904761905, 'Neg Score': 0.09447777777777779, 'Neut Score': 0.8138873015873016, 'Oldest Tweet': 'Tue Jul 03 01:55:44 +0000 2018'}\n",
      "-----\n",
      "{'Airline': '@Virginatlantic', 'Compound Score': 0.18520114942528734, 'Pos Score': 0.1284367816091954, 'Neg Score': 0.04170306513409961, 'Neut Score': 0.8298563218390804, 'Oldest Tweet': 'Thu Jul 05 06:21:49 +0000 2018'}\n",
      "-----\n",
      "{'Airline': '@Delta', 'Compound Score': 0.07331712439418415, 'Pos Score': 0.10621809369951533, 'Neg Score': 0.06991760904684975, 'Neut Score': 0.8238610662358643, 'Oldest Tweet': 'Fri Jul 06 22:14:28 +0000 2018'}\n",
      "-----\n",
      "{'Airline': '@AlaskaAir', 'Compound Score': 0.34695764895330117, 'Pos Score': 0.15877455716586153, 'Neg Score': 0.06719645732689211, 'Neut Score': 0.7740305958132045, 'Oldest Tweet': 'Fri Jul 06 02:17:28 +0000 2018'}\n",
      "-----\n",
      "{'Airline': '@KLM', 'Compound Score': 0.07203647416413374, 'Pos Score': 0.09504559270516717, 'Neg Score': 0.05163829787234043, 'Neut Score': 0.8533161094224924, 'Oldest Tweet': 'Thu Jul 05 20:26:51 +0000 2018'}\n",
      "-----\n",
      "{'Airline': '@FlyFrontier', 'Compound Score': -0.02389560606060606, 'Pos Score': 0.07583787878787879, 'Neg Score': 0.09030151515151516, 'Neut Score': 0.8338515151515151, 'Oldest Tweet': 'Tue Jul 03 05:43:57 +0000 2018'}\n",
      "-----\n"
     ]
    }
   ],
   "source": [
    "# Target Search Term\n",
    "target_terms = (\"@SouthwestAir\", \"@AmericanAir\", \"@SpiritAirlines\",\n",
    "                \"@Virginatlantic\", \"@Delta\", \"@AlaskaAir\", \"@KLM\", \"@FlyFrontier\")\n",
    "\n",
    "# \"Real Person\" Filters\n",
    "min_tweets = 5\n",
    "max_tweets = 10000\n",
    "max_followers = 2500\n",
    "max_following = 2500\n",
    "lang = \"en\"\n",
    "\n",
    "# List to hold sentiment\n",
    "results_list = []\n",
    "\n",
    "# Loop through all target users\n",
    "for target in target_terms:\n",
    "\n",
    "    # Variable for holding the oldest tweet\n",
    "    oldest_tweet = None\n",
    "\n",
    "    # Variables for holding sentiments\n",
    "    compound_list = []\n",
    "    positive_list = []\n",
    "    negative_list = []\n",
    "    neutral_list = []\n",
    "\n",
    "    # Loop through 10 times\n",
    "    for x in range(10):\n",
    "\n",
    "        # Run search around each tweet\n",
    "        public_tweets = api.search(target, \n",
    "                               count=100, \n",
    "                               result_type=\"recent\", \n",
    "                               max_id=oldest_tweet)\n",
    "\n",
    "        # Loop through all tweets\n",
    "        for tweet in public_tweets[\"statuses\"]: #only gets the keys that are nested within statuses.\n",
    "\n",
    "            # Use filters to check if user meets conditions\n",
    "            if (tweet[\"user\"][\"statuses_count\"] > min_tweets and\n",
    "                tweet[\"user\"][\"statuses_count\"] < max_tweets and\n",
    "                tweet[\"user\"][\"friends_count\"] < max_following and\n",
    "                tweet[\"user\"][\"followers_count\"] < max_followers and\n",
    "                tweet[\"user\"][\"lang\"] == lang):\n",
    "\n",
    "                # Run Vader Analysis on each tweet\n",
    "                    results = analyzer.polarity_scores(tweet[\"text\"])\n",
    "\n",
    "                # Add each value to the appropriate list\n",
    "                    compound_list.append(results[\"compound\"])\n",
    "                    positive_list.append(results[\"pos\"])\n",
    "                    negative_list.append(results[\"neg\"])\n",
    "                    neutral_list.append(results[\"neu\"])\n",
    "                \n",
    "            # Set the new oldest_tweet value\n",
    "            oldest_tweet = tweet[\"id\"] - 1\n",
    "            oldest_tweeter = tweet[\"created_at\"]\n",
    "\n",
    "    # Create a dictionary of the Average Sentiments\n",
    "    airline_results = {\"Airline\":target,\n",
    "                      \"Compound Score\":np.mean(compound_list),\n",
    "                      \"Pos Score\":np.mean(positive_list),\n",
    "                      \"Neg Score\":np.mean(negative_list),\n",
    "                      \"Neut Score\":np.mean(neutral_list),\n",
    "                      \"Oldest Tweet\":oldest_tweeter}\n",
    "\n",
    "    # Print the Sentiments\n",
    "    print(airline_results)\n",
    "    print(\"-----\")\n",
    "    \n",
    "    # Append the dictionary to results_list\n",
    "    results_list.append(airline_results)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 17,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>Compound Score</th>\n",
       "      <th>Neg Score</th>\n",
       "      <th>Neut Score</th>\n",
       "      <th>Oldest Tweet</th>\n",
       "      <th>Pos Score</th>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Airline</th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>@FlyFrontier</th>\n",
       "      <td>-0.024</td>\n",
       "      <td>0.090</td>\n",
       "      <td>0.834</td>\n",
       "      <td>Tue Jul 03 05:43:57 +0000 2018</td>\n",
       "      <td>0.076</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>@SpiritAirlines</th>\n",
       "      <td>-0.013</td>\n",
       "      <td>0.094</td>\n",
       "      <td>0.814</td>\n",
       "      <td>Tue Jul 03 01:55:44 +0000 2018</td>\n",
       "      <td>0.092</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>@AmericanAir</th>\n",
       "      <td>0.016</td>\n",
       "      <td>0.080</td>\n",
       "      <td>0.834</td>\n",
       "      <td>Sat Jul 07 02:51:54 +0000 2018</td>\n",
       "      <td>0.086</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>@KLM</th>\n",
       "      <td>0.072</td>\n",
       "      <td>0.052</td>\n",
       "      <td>0.853</td>\n",
       "      <td>Thu Jul 05 20:26:51 +0000 2018</td>\n",
       "      <td>0.095</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>@Delta</th>\n",
       "      <td>0.073</td>\n",
       "      <td>0.070</td>\n",
       "      <td>0.824</td>\n",
       "      <td>Fri Jul 06 22:14:28 +0000 2018</td>\n",
       "      <td>0.106</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>@SouthwestAir</th>\n",
       "      <td>0.162</td>\n",
       "      <td>0.052</td>\n",
       "      <td>0.816</td>\n",
       "      <td>Fri Jul 06 17:00:39 +0000 2018</td>\n",
       "      <td>0.131</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>@Virginatlantic</th>\n",
       "      <td>0.185</td>\n",
       "      <td>0.042</td>\n",
       "      <td>0.830</td>\n",
       "      <td>Thu Jul 05 06:21:49 +0000 2018</td>\n",
       "      <td>0.128</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>@AlaskaAir</th>\n",
       "      <td>0.347</td>\n",
       "      <td>0.067</td>\n",
       "      <td>0.774</td>\n",
       "      <td>Fri Jul 06 02:17:28 +0000 2018</td>\n",
       "      <td>0.159</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "                 Compound Score  Neg Score  Neut Score  \\\n",
       "Airline                                                  \n",
       "@FlyFrontier             -0.024      0.090       0.834   \n",
       "@SpiritAirlines          -0.013      0.094       0.814   \n",
       "@AmericanAir              0.016      0.080       0.834   \n",
       "@KLM                      0.072      0.052       0.853   \n",
       "@Delta                    0.073      0.070       0.824   \n",
       "@SouthwestAir             0.162      0.052       0.816   \n",
       "@Virginatlantic           0.185      0.042       0.830   \n",
       "@AlaskaAir                0.347      0.067       0.774   \n",
       "\n",
       "                                   Oldest Tweet  Pos Score  \n",
       "Airline                                                     \n",
       "@FlyFrontier     Tue Jul 03 05:43:57 +0000 2018      0.076  \n",
       "@SpiritAirlines  Tue Jul 03 01:55:44 +0000 2018      0.092  \n",
       "@AmericanAir     Sat Jul 07 02:51:54 +0000 2018      0.086  \n",
       "@KLM             Thu Jul 05 20:26:51 +0000 2018      0.095  \n",
       "@Delta           Fri Jul 06 22:14:28 +0000 2018      0.106  \n",
       "@SouthwestAir    Fri Jul 06 17:00:39 +0000 2018      0.131  \n",
       "@Virginatlantic  Thu Jul 05 06:21:49 +0000 2018      0.128  \n",
       "@AlaskaAir       Fri Jul 06 02:17:28 +0000 2018      0.159  "
      ]
     },
     "execution_count": 17,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# Create a DataFrame using results_list and display\n",
    "Total_results = pd.DataFrame(results_list).set_index(\"Airline\").round(3)\n",
    "Total_results = Total_results.sort_values(\"Compound Score\", ascending=True)\n",
    "Total_results"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.6.4"
  },
  "varInspector": {
   "cols": {
    "lenName": 16,
    "lenType": 16,
    "lenVar": 40
   },
   "kernels_config": {
    "python": {
     "delete_cmd_postfix": "",
     "delete_cmd_prefix": "del ",
     "library": "var_list.py",
     "varRefreshCmd": "print(var_dic_list())"
    },
    "r": {
     "delete_cmd_postfix": ") ",
     "delete_cmd_prefix": "rm(",
     "library": "var_list.r",
     "varRefreshCmd": "cat(var_dic_list()) "
    }
   },
   "types_to_exclude": [
    "module",
    "function",
    "builtin_function_or_method",
    "instance",
    "_Feature"
   ],
   "window_display": false
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
